#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 6/4/24 11:50 AM
---

local tf = require "tf_module"

local function set_state()
    local cmd = "uci set snmpd.general.enabled=" .. arg[2]
    tf.executeCommand(cmd)
end

local function set_port()
    local cmd = ""
    local str1 = "snmpd.@agent[0].agentaddres='UDP:"
    local str2 = ",UDP6:161"
    cmd = str1 .. str2
    cmd = "uci set " .. str1 .. arg[2] .. str2
    tf.executeCommand(cmd)
end

local function set_read_com()
    local str1 = "uci set snmpd."
    local cmd = str1 .. "read.community=" .. arg[2]
    tf.executeCommand(cmd)
    cmd = ""
    cmd = str1 .. "read_group.group=" .. arg[2]
    tf.executeCommand(cmd)
    cmd = ""
    cmd = str1 .. "public_access.group=" .. arg[2]
    tf.executeCommand(cmd)
end

local function set_write_com()
    local str1 = "uci set snmpd."
    local cmd = str1 .. "write.community=" .. arg[2]
    tf.executeCommand(cmd)

    cmd = ""
    cmd = str1 .. "write_group.group=" .. arg[2]
    tf.executeCommand(cmd)

    cmd = ""
    cmd = str1 .. "private_access.group=" .. arg[2]
    tf.executeCommand(cmd)
end

local function set_version()
    local str1 = "uci set snmpd."
    local cmd = str1 .. "read_group.version=" .. arg[2]
    tf.executeCommand(cmd)

    cmd = ""
    cmd = str1 .. "write_group.version=" .. arg[2]
    tf.executeCommand(cmd)

    cmd = ""
    cmd = str1 .. "public_access.version=" .. arg[2]
    tf.executeCommand(cmd)

    cmd = ""
    cmd = str1 .. "private_access.version=" .. arg[2]
    tf.executeCommand(cmd)
end

local snmp_cmdList =
{
    { cmd = "state",       func = set_state },
    { cmd = "port",        func = set_port },
    { cmd = "read_com",    func = set_read_com },
    { cmd = "write_com",   func = set_write_com },
    { cmd = "version",     func = set_version },
}

local function run_config_snmp()
    local errorCode = 0
    errorCode = tf.validateParam(2, arg)
    if errorCode == 0 then
        for _, value in pairs(snmp_cmdList) do
            if arg[1] == value.cmd then
                value.func()
            end
        end
    end
end

run_config_snmp()
