#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 6/3/24 4:23 PM
---

local tf = require "tf_module"

local descr_type = arg[1]
local str1 = "system.system."
local cmd = str1
local value = "\'"

local function set_description()
    cmd = cmd .. descr_type .. "="
    for i = 2, 7 do
        if arg[i] == nil then
            break
        else
            value = value .. arg[i] .. " "
        end
    end
    value = value .. "\'"
    cmd = "uci set " .. cmd .. value
    tf.executeCommand(cmd)
end

set_description()
