#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 6/3/24 2:18 PM
---

local tf = require "tf_module"

local ipif_struct =
{
    if_name     = "",
    proto       = "",
    IP_addr     = "",
    netmask_IP  = "",
    gateway_IP  = "",
    dns_IP      = "",
}

local function set_ipif_param()
    local if_name    = arg[1]
    local cmd        = arg[2]
    local value      = arg[3]

    --print("cmd = " .. cmd .. " value = " .. value)

    if cmd == "proto" and value == "dhcp" then
        cmd = "uci del network." .. if_name .. ".ipaddr"
        tf.executeCommand(cmd)
        cmd = "uci del network." .. if_name .. ".netmask"
        tf.executeCommand(cmd)
        cmd = "uci del network." .. if_name .. ".ip6assign"
        tf.executeCommand(cmd)
        cmd = "uci set network." .. if_name .. ".proto=\'dhcp\'"
        tf.executeCommand(cmd)

    else
        if cmd == "proto" and value == "static" then
            cmd = "uci set network." .. if_name .. ".proto=\'static\'"
            tf.executeCommand(cmd)
        end
        if cmd == "ip" then
            cmd = "uci set network." .. if_name .. ".ipaddr=" .. value
            tf.executeCommand(cmd)
        elseif cmd == "netmask" then
            cmd = "uci set network." .. if_name .. ".netmask=" .. value
            tf.executeCommand(cmd)
        elseif cmd == "gateway" then
            cmd = "uci set network." .. if_name .. ".gateway=" .. value
            tf.executeCommand(cmd)
        elseif cmd == "dns" then
            cmd = "uci set network." .. if_name .. ".dns=" .. value
            tf.executeCommand(cmd)
        end
    end
end

set_ipif_param()
