#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 6/3/24 4:52 PM

local portRange  = {}
local cmd_in     = ""
local value_in   = ""

local tf    = require "tf_module"
local utils = require "tf_utilities"


local function ar_setParam()
    local status = true
    if cmd_in == "host" then
        status = utils.is_valid_ip(value_in)
    elseif cmd_in == "timeUp" or cmd_in == "timeDown" then
        status = utils.is_valid_time(value_in)
    end

    if status == true then
        for i = portRange[1], portRange[2] do
            local setStateCmd = "uci set tf_autorestart.lan" .. tostring(i) .. "." .. tostring(cmd_in) .. "=" .. tostring(value_in)
            tf.executeCommand(setStateCmd)
        end
    end
end

local function run_config_ar()
    local errorCode = 0

    errorCode = tf.validateParam(3, arg)
    if errorCode == 0 then
        cmd_in   = arg[1]
        value_in = arg[3]

        portRange = tf.checkPortRange(arg[2])
        if portRange ~= nil and portRange ~= "switch" then
            ar_setParam()
        else
            print("Port range is wrong")
        end
    end
end

run_config_ar()







