---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 7/31/24 2:28 PM
---


local str = "switch.1"
if str:find("%.") then
    str = str:gsub("%.", "")  -- убираем точку из строки
end
local str_dot = str:gsub(".", "")
local prefix, number = str:match("(%a+)(%d+)")
print("dot : " .. str_dot)
print("Prefix: " .. prefix)
print("Number: " .. number)

